name: M2 Coding Standard
on: [push, pull_request]

jobs:
  phpcs:
    name: M2 Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: extdn/github-actions-m2/magento-coding-standard/8.1@master
        with:
          phpcs_severity: 10
          phpcs_report: full

  phpmd:
    name: M2 Mess Detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: extdn/github-actions-m2/magento-mess-detector@master

  phpstan:
    name: M2 PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker://extdn/magento-phpstan-action:8.2-latest
        with:
          composer_name: alekseon/widget-forms-cloudflare-turnstile
          composer_version: 2
          phpstan_level: 2
