name: Magento Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: magento
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host=localhost --user=root --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: mbstring, intl, bcmath, gd, pdo_mysql
          coverage: none

      - name: Install Composer
        run: composer self-update && composer install --no-interaction

      - name: Install Magento
        run: |
          composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition magento
          cd magento
          bin/magento setup:install \
            --base-url=http://localhost \
            --db-host=127.0.0.1 \
            --db-name=magento \
            --db-user=root \
            --db-password=root \
            --admin-firstname=admin \
            --admin-lastname=admin \
            --admin-email=admin@example.com \
            --admin-user=admin \
            --admin-password=admin123 \
            --language=en_US \
            --currency=USD \
            --timezone=America/New_York \
            --backend-frontname=admin

      - name: Enable module
        run: |
          cd magento
          composer require alekseon/widget-forms-cloudflare-turnstile
          bin/magento module:enable Alekseon_WidgetFormsCloudflareTurnstile
          bin/magento setup:upgrade

      - name: Run Magento Integration Tests
        run: |
          cd magento/dev/tests/integration
          ../../../vendor/bin/phpunit -c phpunit.xml.dist
